apiVersion: databases.wise2c.com/v1
kind: Mysql
metadata:
  name: mysql-sample
spec:
  # Add fields here
  image: mysql:5.7
  rootPassword: root123
  volumePath: /data/mysql
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - blackbird
          - key: kubernetes.io/os
            operator: In
            values:
            - linux
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: cr
            operator: In
            values:
            - mysql
        topologyKey: kubernetes.io/hostname

